vim.api.nvim_set_keymap('n', '<C-f>', ':NERDTreeFocus<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-n>', ':NERDTree<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-t>', ':NERDTreeToggle<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-PageUp>', ':bp<CR>', {noremap = true})
vim.api.nvim_set_keymap('n', '<C-PageDown>', ':bn<CR>', {noremap = true})
